"""
FlywaySqlGenerator
==================
Deterministic SQL generator for Flyway migrations.

Generates from the domain model:
  V1__create_tables.sql   — CREATE TABLE for every entity
  V2__insert_test_data.sql — 3-5 sample rows per table

Field type mapping (domain → PostgreSQL):
  String / *Status / *Type / *Kind / *State  → VARCHAR(255)
  UUID / *Id VO                              → UUID
  Integer / Long / int / long                → BIGINT
  Double / Float / double / float            → DECIMAL(10,2)
  BigDecimal / Money / Price / Amount        → DECIMAL(15,2)
  Boolean / boolean                          → BOOLEAN
  LocalDate                                  → DATE
  LocalDateTime / Instant                    → TIMESTAMP
"""

from __future__ import annotations
import random
import uuid
from datetime import date, datetime, timedelta


# ── Domain type → PostgreSQL column type ──────────────────────────────────────

_TYPE_MAP = {
    "String": "VARCHAR(255)",
    "UUID": "UUID",
    "Integer": "BIGINT",
    "Long": "BIGINT",
    "int": "BIGINT",
    "long": "BIGINT",
    "Double": "DECIMAL(10,2)",
    "Float": "DECIMAL(10,2)",
    "double": "DECIMAL(10,2)",
    "float": "DECIMAL(10,2)",
    "BigDecimal": "DECIMAL(15,2)",
    "Money": "DECIMAL(15,2)",
    "Price": "DECIMAL(15,2)",
    "Amount": "DECIMAL(15,2)",
    "Boolean": "BOOLEAN",
    "boolean": "BOOLEAN",
    "LocalDate": "DATE",
    "LocalDateTime": "TIMESTAMP",
    "Instant": "TIMESTAMP",
}

_SUFFIX_MAP = [
    (("Status", "Type", "Kind", "State", "Category", "Role", "Name"), "VARCHAR(100)"),
    (("Id",), "UUID"),
    (("Date",), "DATE"),
    (("At", "Time", "DateTime"), "TIMESTAMP"),
    (("Amount", "Price", "Cost", "Total", "Balance", "Fee"), "DECIMAL(15,2)"),
    (("Count", "Number", "Qty", "Quantity"), "BIGINT"),
]


def _pg_type(java_type: str, field_name: str = "") -> str:
    if not java_type:
        return "VARCHAR(255)"
    outer = java_type.split("<")[0]
    if outer in _TYPE_MAP:
        return _TYPE_MAP[outer]
    # Value object suffix heuristics on the type name
    for suffixes, pg in _SUFFIX_MAP:
        if any(outer.endswith(s) for s in suffixes):
            return pg
    # Field name heuristics
    fname = field_name or ""
    for suffixes, pg in _SUFFIX_MAP:
        if any(fname.endswith(s) or fname.lower().endswith(s.lower()) for s in suffixes):
            return pg
    if java_type.startswith("List<") or java_type.startswith("Set<"):
        return None  # skip collection fields
    return "VARCHAR(255)"


def _table_name(entity: str) -> str:
    """'AppointmentStatus' → 'appointment_status'"""
    import re
    s = re.sub(r"([A-Z])", r"_\1", entity).lstrip("_").lower()
    return s


def _col_name(field: str) -> str:
    import re
    s = re.sub(r"([A-Z])", r"_\1", field).lstrip("_").lower()
    return s


# ── DDL generator ──────────────────────────────────────────────────────────────

class FlywaySqlGenerator:

    def generate_v1_create_tables(self, domain_model: dict) -> str:
        dm = domain_model.get("domain_model", domain_model)
        entities = dm.get("entities", [])
        modules = dm.get("modules", {})

        # Collect entity names that appear in modules (to respect ordering)
        module_entities: list[str] = []
        for mod in modules.values():
            if isinstance(mod, dict):
                for e in mod.get("entities", []):
                    if isinstance(e, str) and e not in module_entities:
                        module_entities.append(e)

        # Build entity → fields map
        entity_map: dict[str, list] = {}
        for e in entities:
            if isinstance(e, dict) and e.get("name"):
                entity_map[e["name"]] = e.get("fields", [])

        ordered = [e for e in module_entities if e in entity_map]
        for e in entity_map:
            if e not in ordered:
                ordered.append(e)

        blocks = [
            "-- ============================================================",
            "-- V1: Schema creation (generated by AI Software Factory)",
            "-- ============================================================",
            "",
        ]

        for entity_name in ordered:
            fields = entity_map[entity_name]
            table = _table_name(entity_name)
            cols = ["    id UUID PRIMARY KEY DEFAULT gen_random_uuid()"]

            for f in fields:
                fname = f.get("name", "")
                ftype = f.get("type", "String")
                if fname in ("id",):
                    continue
                pg = _pg_type(ftype, fname)
                if pg is None:
                    continue  # skip List/Set fields
                col = _col_name(fname)
                cols.append(f"    {col} {pg}")

            # Audit columns — always present
            cols += [
                "    created_at  TIMESTAMP",
                "    updated_at  TIMESTAMP",
                "    created_by  VARCHAR(100)",
                "    updated_by  VARCHAR(100)",
            ]

            cols_str = ",\n".join(cols)
            blocks.append(f"CREATE TABLE {table} (\n{cols_str}\n);\n")

        return "\n".join(blocks)

    # ── Seed data ────────────────────────────────────────────────────────────

    def generate_v2_seed_data(self, domain_model: dict, project_name: str) -> str:
        dm = domain_model.get("domain_model", domain_model)
        entities = dm.get("entities", [])
        modules = dm.get("modules", {})

        module_entities: list[str] = []
        for mod in modules.values():
            if isinstance(mod, dict):
                for e in mod.get("entities", []):
                    if isinstance(e, str) and e not in module_entities:
                        module_entities.append(e)

        entity_map: dict[str, list] = {}
        for e in entities:
            if isinstance(e, dict) and e.get("name"):
                entity_map[e["name"]] = e.get("fields", [])

        ordered = [e for e in module_entities if e in entity_map]
        for e in entity_map:
            if e not in ordered:
                ordered.append(e)

        blocks = [
            "-- ============================================================",
            f"-- V2: Test data for {project_name} (generated by AI Software Factory)",
            "-- ============================================================",
            "",
        ]

        # Keep generated UUIDs per entity so foreign keys can reference them
        entity_uuids: dict[str, list[str]] = {}

        for entity_name in ordered:
            fields = entity_map[entity_name]
            table = _table_name(entity_name)
            rows = self._generate_rows(entity_name, fields, 4, entity_uuids)
            entity_uuids[entity_name] = [r["id"] for r in rows]

            if not rows:
                continue

            # Build INSERT
            col_names = list(rows[0].keys())
            cols_str = ", ".join(col_names)

            value_rows = []
            for row in rows:
                vals = []
                for col in col_names:
                    v = row[col]
                    if v is None:
                        vals.append("NULL")
                    elif isinstance(v, bool):
                        vals.append("TRUE" if v else "FALSE")
                    elif isinstance(v, (int, float)):
                        vals.append(str(v))
                    else:
                        escaped = str(v).replace("'", "''")
                        vals.append(f"'{escaped}'")
                value_rows.append(f"    ({', '.join(vals)})")

            values_str = ",\n".join(value_rows)
            blocks.append(
                f"INSERT INTO {table} ({cols_str}) VALUES\n{values_str};\n"
            )

        return "\n".join(blocks)

    # ── Row generator ─────────────────────────────────────────────────────────

    _FIRST_NAMES = ["Ana", "Carlos", "María", "Pedro", "Laura", "Juan", "Elena", "Miguel"]
    _LAST_NAMES = ["García", "Martínez", "López", "Sánchez", "González", "Fernández"]
    _STATUS_VALUES = ["ACTIVE", "INACTIVE", "PENDING", "CONFIRMED", "CANCELLED"]
    _TYPE_VALUES = ["TYPE_A", "TYPE_B", "TYPE_C"]

    def _generate_rows(
        self, entity: str, fields: list, count: int, entity_uuids: dict
    ) -> list[dict]:
        rows = []
        for i in range(count):
            row: dict = {"id": str(uuid.uuid4())}
            for f in fields:
                fname = f.get("name", "")
                ftype = f.get("type", "String")
                if fname == "id":
                    continue
                pg = _pg_type(ftype, fname)
                if pg is None:
                    continue
                col = _col_name(fname)
                row[col] = self._sample_value(fname, ftype, pg, i, entity_uuids)
            rows.append(row)
        return rows

    def _sample_value(self, fname: str, ftype: str, pg: str, idx: int, entity_uuids: dict):
        outer = ftype.split("<")[0]
        fname_l = fname.lower()

        # Foreign keys: try to reference existing entity UUIDs
        if outer.endswith("Id") and len(outer) > 2:
            ref_entity = outer[:-2]  # e.g. "PatientId" → "Patient"
            if ref_entity in entity_uuids and entity_uuids[ref_entity]:
                uuids = entity_uuids[ref_entity]
                return uuids[idx % len(uuids)]
            return str(uuid.uuid4())

        if pg == "UUID":
            return str(uuid.uuid4())

        if pg in ("BIGINT",):
            return random.randint(1, 999)

        if pg in ("DECIMAL(10,2)", "DECIMAL(15,2)"):
            return round(random.uniform(10.0, 500.0), 2)

        if pg == "BOOLEAN":
            return idx % 2 == 0

        if pg == "DATE":
            d = date.today() - timedelta(days=random.randint(0, 365))
            return d.isoformat()

        if pg == "TIMESTAMP":
            dt = datetime.now() - timedelta(days=random.randint(0, 90),
                                             hours=random.randint(0, 23))
            return dt.strftime("%Y-%m-%d %H:%M:%S")

        # VARCHAR — heuristic by field name
        if "name" in fname_l or "nombre" in fname_l:
            parts = self._FIRST_NAMES[idx % len(self._FIRST_NAMES)]
            return parts

        if "lastname" in fname_l or "surname" in fname_l or "apellido" in fname_l:
            return self._LAST_NAMES[idx % len(self._LAST_NAMES)]

        if "email" in fname_l:
            return f"user{idx + 1}@example.com"

        if "phone" in fname_l or "telefono" in fname_l:
            return f"+34 6{random.randint(10, 99)} {random.randint(100, 999)} {random.randint(100, 999)}"

        if "address" in fname_l or "direccion" in fname_l:
            return f"Calle Mayor {idx + 1}, Madrid"

        if "description" in fname_l or "descripcion" in fname_l or "notes" in fname_l:
            return f"Sample {fname} {idx + 1}"

        if any(fname_l.endswith(s.lower()) for s in ("Status", "Type", "Kind", "State", "Category", "Role")):
            return self._STATUS_VALUES[idx % len(self._STATUS_VALUES)]

        return f"value_{idx + 1}"
