-- ============================================================
-- V2: Test data for dentalclinic (generated by AI Software Factory)
-- ============================================================

INSERT INTO appointment (id, appointment_id, patient_id, dentist_id, appointment_date, status) VALUES
    ('0331fde8-92ae-40de-840f-e92e2f16fd01', '5a275fcd-a052-441f-b0ac-c430a8535ba7', '898d30d7-10fc-426f-b27b-dcc22f4dabcd', 'ce0ee55d-94b2-4406-8f87-a3d7a3e262fa', '2026-01-25 13:09:55', 'ACTIVE'),
    ('1c77a644-c9ff-4d74-9db2-497750ee9e5a', 'edaceb9b-6705-47bf-8581-5e7e191e644c', '7f248b0d-f97c-4e1c-aab3-93d379b1c891', 'bdb39df1-f784-4a40-8f04-d145b7bdd47b', '2026-02-03 15:09:55', 'INACTIVE'),
    ('0d0ac59e-fb8a-4e4a-afbf-5d1e6152fc39', 'f5ef6a81-bf06-4f87-beb8-cdd589dfd69d', '73dfce9f-f718-4f83-a275-6f069789073d', '67f72de7-5608-4fa9-bd81-8e292d1ad87a', '2026-03-06 09:09:55', 'PENDING'),
    ('3c1fee1e-423c-43e7-97ee-56f554fbe61e', '31d95326-ca8f-44a5-82ec-85235e078472', '21ccba26-77de-49d6-89af-f5f362bb4308', '60daf6b8-2d61-4d87-952a-9998bd12f9a7', '2026-03-08 04:09:55', 'CONFIRMED');

INSERT INTO patient (id, first_name, last_name, birth_date, patient_id) VALUES
    ('7c8a6c02-6256-4524-bfce-1a05a0abf43e', 'Ana', 'Ana', '2025-08-11', '04bb79f7-8d71-4157-9263-502d1e77c10b'),
    ('578dac69-70aa-46d2-b950-3274834ec403', 'Carlos', 'Carlos', '2025-11-07', '4ae0273b-7581-4e8d-bb21-140da134fcef'),
    ('56b7c2be-4367-4bbf-a306-de0af17c41ec', 'María', 'María', '2025-12-26', 'dfaac308-972d-43bb-b805-f88adac06c23'),
    ('e1230a8b-448a-4124-9b45-9c9337019df5', 'Pedro', 'Pedro', '2025-11-29', '66ee514f-5a5e-4b05-a9c3-d9a84e460e2f');

INSERT INTO dentist (id, first_name, last_name, license_number, dentist_id) VALUES
    ('d220fdf6-2d61-4bdc-ab36-3f5938e6f5bf', 'Ana', 'Ana', 'value_1', '67833a63-5817-4242-856f-f6cc74ece1d7'),
    ('ee96b930-ca01-495c-b5ad-8ecf853a431d', 'Carlos', 'Carlos', 'value_2', '4c77a204-b62a-4f8e-a2ba-d3e56eedd20a'),
    ('0dba8f20-d504-4892-98d6-f85bc47bc2eb', 'María', 'María', 'value_3', 'f04387dc-711d-46cd-9c56-7e702b66914d'),
    ('26702571-fcd2-4441-938c-ff073a245eac', 'Pedro', 'Pedro', 'value_4', 'e957004b-75cb-4bb7-928c-477e00e0b682');

INSERT INTO treatment (id, treatment_id, appointment_id, description, cost) VALUES
    ('f5a1561b-d39e-4477-acc5-129a53071104', '2effd853-c584-47db-a329-8459a30521bb', 'cad3d3e1-5bf3-42d5-96f4-96f6448e1bf4', 'Sample description 1', 160.99),
    ('053e0fb3-3d63-448e-9eff-43e39fe0681d', '2f89785d-531d-4ae7-9b06-94fab130776e', 'e089c3ad-d035-4cc8-a30b-c858f7df8fff', 'Sample description 2', 461.54),
    ('c9954385-c6ff-4021-a1fa-d8ab971d5316', 'ec664636-b982-4da5-b330-80a4f9902bc2', 'e3100573-9eb3-4416-8f90-afa597ce59e1', 'Sample description 3', 355.8),
    ('d5dd4166-72f7-4710-999f-a47b1c29745f', '9c46b329-a523-4128-adad-7b58dfbb5080', 'f548b6b8-66cb-4914-b25e-bed9d2ed8945', 'Sample description 4', 185.89);

INSERT INTO invoice (id, invoice_id, patient_id, amount, status, issue_date) VALUES
    ('fdce4d6f-d00a-4e0b-b8d0-901fd7bcd174', '21948176-3c16-418d-814e-e6331483b4b0', '614b3b8c-8d69-4465-b3d0-e6a3ee97389a', 432.51, 'ACTIVE', '2025-11-25'),
    ('7ca16138-6f35-40cb-bf0a-25454f62c542', 'b7b66a46-e6e4-4b79-9d8d-be931fcd1d71', '364061f4-ecf6-4bb6-94a2-d367c96c5c6d', 23.29, 'INACTIVE', '2026-03-15'),
    ('f3b810a6-52cd-4e45-b99e-f07f6d133263', '1cdcf3df-1e00-4681-adc5-e3469dd0ec30', '0dfaa6c8-d577-43aa-8f93-5a340417fb52', 383.52, 'PENDING', '2025-06-30'),
    ('3ce7eb43-ff3b-466b-a7b1-e09a7ac032f1', 'af3615e4-e698-42b4-bc69-0963bf29e1a0', '6eb05bf7-65be-41e9-8def-904c88858445', 287.65, 'CONFIRMED', '2025-10-31');
